-- 1. BẢNG KHOA
CREATE TABLE KHOA (
    MaKhoa VARCHAR(10) NOT NULL,
    TenKhoa NVARCHAR(100) NOT NULL,
    DienThoaiKhoa VARCHAR(15) NULL,
    EmailKhoa VARCHAR(100) NOT NULL,
    
    CONSTRAINT PK_KHOA PRIMARY KEY (MaKhoa),
    CONSTRAINT UQ_KHOA_TenKhoa UNIQUE (TenKhoa),
    CONSTRAINT UQ_KHOA_EmailKhoa UNIQUE (EmailKhoa)
);

-- 2. BẢNG NGANH
CREATE TABLE NGANH (
    MaNganh VARCHAR(10) NOT NULL,
    TenNganh NVARCHAR(100) NOT NULL,
    ThoiGianDaoTao DECIMAL(3,1) CONSTRAINT DF_NGANH_ThoiGianDaoTao DEFAULT 4.0 NOT NULL,
    MaKhoa VARCHAR(10) NOT NULL,
    
    CONSTRAINT PK_NGANH PRIMARY KEY (MaNganh),
    CONSTRAINT UQ_NGANH_TenNganh UNIQUE (TenNganh),
    CONSTRAINT CK_NGANH_ThoiGianDaoTao CHECK (ThoiGianDaoTao > 0),
    
    -- Ràng buộc ON DELETE NO ACTION cho quan hệ Khoa -> Ngành
    CONSTRAINT FK_NGANH_KHOA FOREIGN KEY (MaKhoa) 
        REFERENCES KHOA(MaKhoa) 
        ON DELETE NO ACTION 
        ON UPDATE CASCADE
);

-- 3. BẢNG LOP
CREATE TABLE LOP (
    MaLop VARCHAR(15) NOT NULL,
    TenLop NVARCHAR(100) NOT NULL,
    NienKhoa INT NOT NULL,
    MaNganh VARCHAR(10) NOT NULL,
    
    CONSTRAINT PK_LOP PRIMARY KEY (MaLop),
    CONSTRAINT CK_LOP_NienKhoa CHECK (NienKhoa BETWEEN 2000 AND 2030),
    CONSTRAINT FK_LOP_NGANH FOREIGN KEY (MaNganh) 
        REFERENCES NGANH(MaNganh) 
        ON DELETE NO ACTION 
        ON UPDATE CASCADE
);

-- 4. BẢNG CHUONGTRINHDAOTAO
CREATE TABLE CHUONGTRINHDAOTAO (
    MaCTDT VARCHAR(10) NOT NULL,
    TenCTDT NVARCHAR(100) NOT NULL,
    NamApDung INT NOT NULL,
    TongSoTinChi INT NOT NULL,
    MaNganh VARCHAR(10) NOT NULL,
    
    CONSTRAINT PK_CHUONGTRINHDAOTAO PRIMARY KEY (MaCTDT),
    CONSTRAINT CK_CTDT_NamApDung CHECK (NamApDung >= 2000),
    CONSTRAINT CK_CTDT_TongSoTinChi CHECK (TongSoTinChi > 0),
    CONSTRAINT FK_CTDT_NGANH FOREIGN KEY (MaNganh) 
        REFERENCES NGANH(MaNganh) 
        ON DELETE NO ACTION 
        ON UPDATE CASCADE
);

-- 5. BẢNG SINH_VIEN
CREATE TABLE SINH_VIEN (
    MaSV VARCHAR(12) NOT NULL,
    HoTen NVARCHAR(100) NOT NULL,
    NgaySinh DATE NOT NULL,
    GioiTinh TINYINT CONSTRAINT DF_SINHVIEN_GioiTinh DEFAULT 1 NOT NULL,
    TrangThaiHoc TINYINT CONSTRAINT DF_SINHVIEN_TrangThaiHoc DEFAULT 1 NOT NULL,
    Email VARCHAR(100) NOT NULL,
    SoDienThoai VARCHAR(15) NOT NULL,
    QueQuan NVARCHAR(100) NULL,
    MaLop VARCHAR(15) NOT NULL,
    
    CONSTRAINT PK_SINH_VIEN PRIMARY KEY (MaSV),
    CONSTRAINT UQ_SINHVIEN_Email UNIQUE (Email),
    
    -- Ràng buộc CHECK miền giá trị cho GioiTinh và TrangThaiHoc
    CONSTRAINT CK_SINHVIEN_GioiTinh CHECK (GioiTinh IN (0, 1)),
    CONSTRAINT CK_SINHVIEN_TrangThaiHoc CHECK (TrangThaiHoc IN (1, 2, 3)),
    
    CONSTRAINT FK_SINHVIEN_LOP FOREIGN KEY (MaLop) 
        REFERENCES LOP(MaLop) 
        ON DELETE NO ACTION 
        ON UPDATE CASCADE
);