
-- 1. BẢNG KHOA
CREATE TABLE KHOA (
    MaKhoa VARCHAR(10) NOT NULL,
    TenKhoa NVARCHAR(100) NOT NULL,
    DienThoaiKhoa VARCHAR(15) NULL,
    EmailKhoa VARCHAR(100) NOT NULL,
    
    CONSTRAINT PK_KHOA PRIMARY KEY (MaKhoa),
    CONSTRAINT UQ_KHOA_TenKhoa UNIQUE (TenKhoa),
    CONSTRAINT UQ_KHOA_EmailKhoa UNIQUE (EmailKhoa)
);

-- 2. BẢNG NGANH
CREATE TABLE NGANH (
    MaNganh VARCHAR(10) NOT NULL,
    TenNganh NVARCHAR(100) NOT NULL,
    ThoiGianDaoTao DECIMAL(3,1) CONSTRAINT DF_NGANH_ThoiGianDaoTao DEFAULT 4.0 NOT NULL,
    MaKhoa VARCHAR(10) NOT NULL,
    
    CONSTRAINT PK_NGANH PRIMARY KEY (MaNganh),
    CONSTRAINT UQ_NGANH_TenNganh UNIQUE (TenNganh),
    CONSTRAINT CK_NGANH_ThoiGianDaoTao CHECK (ThoiGianDaoTao > 0),
    
    -- ON DELETE NO ACTION cho Khoa -> Ngành
    CONSTRAINT FK_NGANH_KHOA FOREIGN KEY (MaKhoa) 
        REFERENCES KHOA(MaKhoa) 
        ON DELETE NO ACTION 
        ON UPDATE CASCADE
);

-- 3. BẢNG LOP
CREATE TABLE LOP (
    MaLop VARCHAR(15) NOT NULL,
    TenLop NVARCHAR(100) NOT NULL,
    NienKhoa INT NOT NULL,
    MaNganh VARCHAR(10) NOT NULL,
    
    CONSTRAINT PK_LOP PRIMARY KEY (MaLop),
    CONSTRAINT CK_LOP_NienKhoa CHECK (NienKhoa BETWEEN 2000 AND 2030),
    CONSTRAINT FK_LOP_NGANH FOREIGN KEY (MaNganh) 
        REFERENCES NGANH(MaNganh) 
        ON DELETE NO ACTION 
        ON UPDATE CASCADE
);

-- 4. BẢNG CHUONGTRINHDAOTAO
CREATE TABLE CHUONGTRINHDAOTAO (
    MaCTDT VARCHAR(10) NOT NULL,
    TenCTDT NVARCHAR(100) NOT NULL,
    NamApDung INT NOT NULL,
    TongSoTinChi INT NOT NULL,
    MaNganh VARCHAR(10) NOT NULL,
    
    CONSTRAINT PK_CHUONGTRINHDAOTAO PRIMARY KEY (MaCTDT),
    CONSTRAINT CK_CTDT_NamApDung CHECK (NamApDung >= 2000),
    CONSTRAINT CK_CTDT_TongSoTinChi CHECK (TongSoTinChi > 0),
    CONSTRAINT FK_CTDT_NGANH FOREIGN KEY (MaNganh) 
        REFERENCES NGANH(MaNganh) 
        ON DELETE NO ACTION 
        ON UPDATE CASCADE
);

-- 5. BẢNG SINH_VIEN
CREATE TABLE SINH_VIEN (
    MaSV VARCHAR(12) NOT NULL,
    HoTen NVARCHAR(100) NOT NULL,
    NgaySinh DATE NOT NULL,
    GioiTinh TINYINT CONSTRAINT DF_SINHVIEN_GioiTinh DEFAULT 1 NOT NULL,
    TrangThaiHoc TINYINT CONSTRAINT DF_SINHVIEN_TrangThaiHoc DEFAULT 1 NOT NULL,
    Email VARCHAR(100) NOT NULL,
    SoDienThoai VARCHAR(15) NOT NULL,
    QueQuan NVARCHAR(100) NULL,
    MaLop VARCHAR(15) NOT NULL,
    
    CONSTRAINT PK_SINH_VIEN PRIMARY KEY (MaSV),
    CONSTRAINT UQ_SINHVIEN_Email UNIQUE (Email),
    
    -- CHECK cho GioiTinh và TrangThaiHoc
    CONSTRAINT CK_SINHVIEN_GioiTinh CHECK (GioiTinh IN (0, 1)),
    CONSTRAINT CK_SINHVIEN_TrangThaiHoc CHECK (TrangThaiHoc IN (1, 2, 3)),
    
    CONSTRAINT FK_SINHVIEN_LOP FOREIGN KEY (MaLop) 
        REFERENCES LOP(MaLop) 
        ON DELETE NO ACTION 
        ON UPDATE CASCADE
);

-- 6. BẢNG MON_HOC
CREATE TABLE MON_HOC (
    MaMH VARCHAR(10) NOT NULL,
    TenMon NVARCHAR(100) NOT NULL,
    SoTinChi INT CONSTRAINT DF_MONHOC_SoTinChi DEFAULT 3 NOT NULL,
    
    CONSTRAINT PK_MON_HOC PRIMARY KEY (MaMH),
    CONSTRAINT UQ_MONHOC_TenMon UNIQUE (TenMon),
    CONSTRAINT CK_MONHOC_SoTinChi CHECK (SoTinChi > 0)
);

-- 7. BẢNG HOC_KY
CREATE TABLE HOC_KY (
    MaHocKy VARCHAR(10) NOT NULL,
    TenHocKy NVARCHAR(50) NOT NULL,
    
    CONSTRAINT PK_HOC_KY PRIMARY KEY (MaHocKy)
);

-- 8. BẢNG CHI_TIET_CTDT
CREATE TABLE CHI_TIET_CTDT (
    MaCTDT VARCHAR(10) NOT NULL,
    MaMH VARCHAR(10) NOT NULL,
    MaHocKy VARCHAR(10) NOT NULL,
    
    -- Khóa chính ghép
    CONSTRAINT PK_CHI_TIET_CTDT PRIMARY KEY (MaCTDT, MaMH),
    
    -- Ràng buộc Khóa ngoại
    CONSTRAINT FK_CTCTDT_CTDT FOREIGN KEY (MaCTDT) 
        REFERENCES CHUONGTRINHDAOTAO(MaCTDT) 
        ON DELETE CASCADE 
        ON UPDATE CASCADE,
        
    CONSTRAINT FK_CTCTDT_MONHOC FOREIGN KEY (MaMH) 
        REFERENCES MON_HOC(MaMH) 
        ON DELETE NO ACTION 
        ON UPDATE CASCADE,
        
    CONSTRAINT FK_CTCTDT_HOCKY FOREIGN KEY (MaHocKy) 
        REFERENCES HOC_KY(MaHocKy) 
        ON DELETE NO ACTION 
        ON UPDATE CASCADE
);